version: "1"
services:
  server:
    container_name: server
    image: server
    restart: always
    build: ./
    networks: 
      - network
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - rabbitmq

  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - '27017:27017'
    tty: true
    networks: 
      - network
  
  updateStatus:
    container_name: updateStatus
    image: update_status
    build: 
      context: ./
      dockerfile: ./updateStatus/Dockerfile
    networks: 
      - network
    depends_on:
      - rabbitmq
      - mongo

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:latest
    ports:
      - "5672:5672"
    networks:
      - network
      
networks:
  network: 
    driver: bridge